### ISSUE TITLE
Synthesize Satellite Imagery

### ISSUE THREAD

**Issue by natowi** [kacebe/AtlantGIS#12]
It would be interesting to synthesize satellite imagery from the DEM.
>Moreover, we used the same network to solve the inverse problem, i.e. predicting the RGB image given a DEM. We received promising results:" 
![grafik](https://user-images.githubusercontent.com/8138537/117532429-c0177100-afe7-11eb-8188-8715ed8d5536.png)
https://github.com/Panagiotou/ImageToDEM

**Comment by kacebe** [comment]
I guess you are referring to digital elevation models stored [in this folder](https://github.com/kacebe/AtlantGIS/tree/master/raster/dem)?
Please note, that the DEM as all other datasets in the AtlantGIS-Repository is a faked GIS-Dataset, simulating an island in the Atlantic for educational purposes in using GIS in archaeology. The idea is to create artificial data creatively referring to the story of Atlantis as told by Platon. 
The **_original_** DEM used for AtlantGIS is from the island of Socotra (SRTM), which you'd have to download yourself [here](https://web.archive.org/web/20150913200035/https://lpdaac.usgs.gov/nasa_shuttle_radar_topography_mission_srtm_global_1_arc_second_data_released_over_middle_east). For ground truthing you might want to use:
[NASA Earth Observatory image by Jesse Allen and Robert Simmon, using EO-1 ALI data provided courtesy of the NASA EO-1 team](https://visibleearth.nasa.gov/images/78411/hajhir-mountains-socotra-island-yemen).

**Comment by natowi** [comment]
I know it is fake data, that´s because it would be interesting to generate fake satellite imagery :D

**Comment by kacebe** [comment]
Warmly welcome! And please keep me updated!
